name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 4.2.2
  EXPORT_NAME: Aetherebirth
  PROJECT_PATH: .

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    permissions: write-all
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop x86_64" ./build/windows/$EXPORT_NAME-x86_64-windows.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aetherebirth-x86_64-windows
          path: build/windows/Aetherebirth-x86_64-windows.exe
      - name: Prerelease with latest tag 
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "windows-latest"
          prerelease: true
          title: "Development Build - Windows"
          files: |
            build/windows/*

  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    permissions: write-all
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Linux/X11 x86_64" ./build/linux/$EXPORT_NAME-x86_64-linux.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aetherebirth-x86_64-linux
          path: build/linux/Aetherebirth-x86_64-linux.x86_64
      - name: Prerelease with latest tag 
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "linux-latest"
          prerelease: true
          title: "Development Build - Linux"
          files: |
            build/linux/*
