name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 4.2.2
  EXPORT_NAME: Aetherebirth
  PROJECT_PATH: .

jobs:
  export:
    name: Export
    runs-on: ubuntu-latest
    permissions: write-all
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Windows Build x86_64
        run: |
          mkdir -v -p build/windows
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop x86_64" ./build/windows/$EXPORT_NAME-x86_64-windows.exe
      - name: Linux Build x86_64
        run: |
          mkdir -v -p build/linux
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Linux/X11 x86_64" ./build/linux/$EXPORT_NAME-x86_64-linux.x86_64

      - name: Prerelease
        uses: softprops/action-gh-release@v2
        with:
          name: "Development Build"
          prerelease: true
          tag_name: latest
          generate_release_notes: true
          files: |
            build/windows/*
            build/linux/*
          token: "${{ secrets.GITHUB_TOKEN }}"
